Version =20
VersionRequired =20
Begin Report
    LayoutForPrint = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    TabularCharSet =162
    TabularFamily =0
    DateGrouping =1
    GrpKeepTogether =1
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =16116
    DatasheetFontHeight =11
    ItemSuffix =528
    RecSrcDt = Begin
        0x0ba005ce7458e640
    End
    RecordSource ="SELECT tbl_AuditReports.Record_year, tbl_AuditReports.Status, tbl_AuditReports.A"
        "uditor_Lead, tbl_AuditReports.Auditor_Asist, tbl_AuditReports.Audit_Report_Numbe"
        "r, tbl_AuditReports.Type_of_Activity, tbl_AuditReports.Previous_Audit_Report_Num"
        "ber, tbl_AuditReports.Previous_Audit_Report_Date, tbl_AuditReports.Location, tbl"
        "_AuditReports.Plan_Revision_Date FROM tbl_AuditReports; "
    DatasheetFontName ="Aptos"
    FilterOnLoad =0
    FitToPage =1
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            TextFontCharSet =162
            FontSize =11
            BorderColor =8355711
            ForeColor =6710886
            FontName ="Aptos"
            GridlineColor =10921638
            ThemeFontIndex =1
            BorderTint =50.0
            ForeTint =60.0
            GridlineShade =65.0
        End
        Begin Rectangle
            BorderLineStyle =0
            Width =850
            Height =850
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin CheckBox
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            TextFontCharSet =162
            TextFontFamily =0
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Aptos"
            AsianLineBreak =1
            ShowDatePicker =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin ListBox
            TextFontCharSet =162
            TextFontFamily =0
            BorderLineStyle =0
            Width =1701
            Height =1417
            LabelX =-1701
            FontSize =11
            FontName ="Aptos"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin ComboBox
            AddColon = NotDefault
            TextFontCharSet =162
            TextFontFamily =0
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Aptos"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin PageHeader
            Height =963
            Name ="PageHeaderSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =5
            BackTint =20.0
            Begin
                Begin Label
                    Left =1164
                    Top =288
                    Width =2784
                    Height =492
                    FontSize =18
                    Name ="Label0"
                    Caption ="Audit Plan Report"
                    LayoutCachedLeft =1164
                    LayoutCachedTop =288
                    LayoutCachedWidth =3948
                    LayoutCachedHeight =780
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =0
                    ForeTint =95.0
                    GridlineThemeColorIndex =1
                End
                Begin TextBox
                    OldBorderStyle =0
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    Left =156
                    Top =228
                    Width =969
                    Height =444
                    FontSize =20
                    FontWeight =700
                    ForeColor =855309
                    Name ="Record_year"
                    ControlSource ="Record_year"

                    LayoutCachedLeft =156
                    LayoutCachedTop =228
                    LayoutCachedWidth =1125
                    LayoutCachedHeight =672
                    ForeTint =95.0
                End
            End
        End
        Begin Section
            KeepTogether = NotDefault
            CanGrow = NotDefault
            Height =3741
            Name ="Detail"
            AlternateBackThemeColorIndex =1
            BackThemeColorIndex =1
            Begin
                Begin Rectangle
                    Left =36
                    Top =1133
                    Width =3391
                    Height =885
                    Name ="Box190"
                    LayoutCachedLeft =36
                    LayoutCachedTop =1133
                    LayoutCachedWidth =3427
                    LayoutCachedHeight =2018
                    BackThemeColorIndex =9
                End
                Begin Rectangle
                    Left =9674
                    Top =1133
                    Width =6391
                    Height =885
                    BackColor =14277081
                    Name ="Box179"
                    LayoutCachedLeft =9674
                    LayoutCachedTop =1133
                    LayoutCachedWidth =16065
                    LayoutCachedHeight =2018
                    BackShade =85.0
                End
                Begin Rectangle
                    Width =16099
                    Height =1077
                    Name ="Box171"
                    LayoutCachedWidth =16099
                    LayoutCachedHeight =1077
                    BackThemeColorIndex =2
                    BackTint =10.0
                End
                Begin Label
                    FontItalic = NotDefault
                    TextAlign =1
                    Left =96
                    Top =108
                    Width =3180
                    Height =324
                    FontSize =9
                    FontWeight =700
                    Name ="Label5"
                    Caption ="Audit Report Number"
                    GroupTable =2
                    BottomPadding =150
                    LayoutCachedLeft =96
                    LayoutCachedTop =108
                    LayoutCachedWidth =3276
                    LayoutCachedHeight =432
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackTint =90.0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    TextAlign =1
                    Left =3336
                    Top =108
                    Width =1188
                    Height =324
                    FontSize =9
                    FontWeight =700
                    Name ="Label78"
                    Caption ="Planned to"
                    GroupTable =2
                    BottomPadding =150
                    LayoutCachedLeft =3336
                    LayoutCachedTop =108
                    LayoutCachedWidth =4524
                    LayoutCachedHeight =432
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackTint =90.0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    FontItalic = NotDefault
                    TextAlign =1
                    Left =4560
                    Top =108
                    Width =1764
                    Height =324
                    FontSize =9
                    FontWeight =700
                    Name ="Label3"
                    Caption ="Auditor "
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =4560
                    LayoutCachedTop =108
                    LayoutCachedWidth =6324
                    LayoutCachedHeight =432
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackTint =90.0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    FontItalic = NotDefault
                    TextAlign =1
                    Left =6324
                    Top =108
                    Width =1584
                    Height =324
                    FontSize =9
                    FontWeight =700
                    Name ="Label4"
                    Caption ="Asistant Auditor"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =6324
                    LayoutCachedTop =108
                    LayoutCachedWidth =7908
                    LayoutCachedHeight =432
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackTint =90.0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin ComboBox
                    LimitToList = NotDefault
                    AutoExpand = NotDefault
                    AllowAutoCorrect = NotDefault
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    ColumnCount =2
                    ListRows =18
                    ListWidth =1440
                    Left =9684
                    Top =108
                    Width =6360
                    Height =324
                    ColumnWidth =5820
                    FontSize =10
                    BoundColumn =1
                    Name ="Type_of_Activity"
                    ControlSource ="Type_of_Activity"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [tbl_type_of_activity].[ID], [tbl_type_of_activity].[Type_of_activity] FR"
                        "OM tbl_type_of_activity; "
                    ColumnWidths ="0;1440"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150

                    LayoutCachedLeft =9684
                    LayoutCachedTop =108
                    LayoutCachedWidth =16044
                    LayoutCachedHeight =432
                    ColumnStart =5
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                    Begin
                        Begin Label
                            FontItalic = NotDefault
                            TextAlign =1
                            Left =7908
                            Top =108
                            Width =1776
                            Height =324
                            FontSize =9
                            FontWeight =700
                            Name ="Label6"
                            Caption ="Operational Area"
                            GroupTable =2
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            LayoutCachedLeft =7908
                            LayoutCachedTop =108
                            LayoutCachedWidth =9684
                            LayoutCachedHeight =432
                            ColumnStart =4
                            ColumnEnd =4
                            LayoutGroup =1
                            BackThemeColorIndex =2
                            BackTint =90.0
                            ForeThemeColorIndex =2
                            ForeTint =90.0
                            GridlineThemeColorIndex =1
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    Left =96
                    Top =612
                    Width =3180
                    Height =324
                    ColumnWidth =3864
                    FontSize =9
                    FontWeight =700
                    TabIndex =1
                    ForeColor =2500134
                    Name ="Audit_Report_Number"
                    ControlSource ="Audit_Report_Number"
                    GroupTable =2
                    BottomPadding =150

                    LayoutCachedLeft =96
                    LayoutCachedTop =612
                    LayoutCachedWidth =3276
                    LayoutCachedHeight =936
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    ForeTint =85.0
                    GroupTable =2
                End
                Begin TextBox
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    Left =3336
                    Top =612
                    Width =1188
                    Height =324
                    ColumnWidth =2172
                    FontSize =10
                    TabIndex =2
                    Name ="Plan_Revision_Date"
                    ControlSource ="Plan_Revision_Date"
                    Format ="Medium Date"
                    GroupTable =2
                    BottomPadding =150
                    ShowDatePicker =1

                    LayoutCachedLeft =3336
                    LayoutCachedTop =612
                    LayoutCachedWidth =4524
                    LayoutCachedHeight =936
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =50.0
                    GroupTable =2
                End
                Begin ComboBox
                    LimitToList = NotDefault
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    ColumnCount =2
                    ListWidth =1440
                    Left =4560
                    Top =612
                    Width =1764
                    Height =324
                    ColumnWidth =2052
                    FontSize =10
                    TabIndex =3
                    Name ="Auditor_Lead"
                    ControlSource ="Auditor_Lead"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [tbl_Auditors].[AuditorID], [tbl_Auditors].[Auditor] FROM tbl_Auditors; "
                    ColumnWidths ="0;1440"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    AllowValueListEdits =0

                    LayoutCachedLeft =4560
                    LayoutCachedTop =612
                    LayoutCachedWidth =6324
                    LayoutCachedHeight =936
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin ComboBox
                    LimitToList = NotDefault
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    ColumnCount =2
                    ListWidth =1440
                    Left =6324
                    Top =612
                    Width =1584
                    Height =324
                    ColumnWidth =1860
                    FontSize =10
                    TabIndex =4
                    Name ="Auditor_Asist"
                    ControlSource ="Auditor_Asist"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [tbl_Auditors].[AuditorID], [tbl_Auditors].[Auditor] FROM tbl_Auditors; "
                    ColumnWidths ="0;1440"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    AllowValueListEdits =0

                    LayoutCachedLeft =6324
                    LayoutCachedTop =612
                    LayoutCachedWidth =7908
                    LayoutCachedHeight =936
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin ComboBox
                    RowSourceTypeInt =1
                    OldBorderStyle =0
                    TextAlign =1
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    ListWidth =1440
                    Left =9684
                    Top =612
                    Width =6360
                    Height =324
                    ColumnWidth =3144
                    FontSize =10
                    TabIndex =5
                    Name ="Location"
                    ControlSource ="Location"
                    RowSourceType ="Value List"
                    RowSource ="\"Aircraft - Base\";\"Aircraft - Line - AYT\";\"Aircraft - Line - SAW\";\"Aircra"
                        "ft - Line\";\"Engine Workshop\";\"Electric and Electronic Shop\";\"Hydraulic Sho"
                        "p\";\"Wheel and Brake Shop\";\"Compressed Cylinder and Regulatory Shop\";\"Struc"
                        "tial and Repair Shop\";\"Emergencs Equipment Shop\";\"NDT\";\"Boroscope Inspecti"
                        "on\";\"Composite Repair\";\"Fabrication of Parts\";\"Painting\";\"Tap Test (Coin"
                        ")\";\"Welding\""
                    ColumnWidths ="1440"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150

                    LayoutCachedLeft =9684
                    LayoutCachedTop =612
                    LayoutCachedWidth =16044
                    LayoutCachedHeight =936
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                    Begin
                        Begin Label
                            FontItalic = NotDefault
                            TextAlign =1
                            Left =7908
                            Top =612
                            Width =1776
                            Height =324
                            FontSize =9
                            FontWeight =700
                            Name ="Label63"
                            Caption ="Functional Area"
                            GroupTable =2
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            LayoutCachedLeft =7908
                            LayoutCachedTop =612
                            LayoutCachedWidth =9684
                            LayoutCachedHeight =936
                            RowStart =1
                            RowEnd =1
                            ColumnStart =4
                            ColumnEnd =4
                            LayoutGroup =1
                            BackThemeColorIndex =2
                            BackTint =90.0
                            ForeThemeColorIndex =2
                            ForeTint =90.0
                            GridlineThemeColorIndex =1
                            GroupTable =2
                        End
                    End
                End
                Begin Label
                    TextAlign =2
                    Left =96
                    Top =1116
                    Width =3180
                    Height =300
                    FontSize =10
                    FontWeight =700
                    Name ="Label2"
                    Caption ="Status"
                    GroupTable =2
                    BottomPadding =150
                    LayoutCachedLeft =96
                    LayoutCachedTop =1116
                    LayoutCachedWidth =3276
                    LayoutCachedHeight =1416
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =3336
                    Top =1116
                    Width =2988
                    Height =300
                    Name ="EmptyCell182"
                    GroupTable =2
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =3336
                    LayoutCachedTop =1116
                    LayoutCachedWidth =6324
                    LayoutCachedHeight =1416
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6324
                    Top =1116
                    Width =3360
                    Height =300
                    Name ="EmptyCell181"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =6324
                    LayoutCachedTop =1116
                    LayoutCachedWidth =9684
                    LayoutCachedHeight =1416
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    TextAlign =2
                    Left =9684
                    Top =1116
                    Width =3132
                    Height =300
                    FontSize =9
                    FontWeight =700
                    Name ="Label61"
                    Caption ="Previous Audit Report Number"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =9684
                    LayoutCachedTop =1116
                    LayoutCachedWidth =12816
                    LayoutCachedHeight =1416
                    RowStart =2
                    RowEnd =2
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    BackThemeColorIndex =5
                    BackTint =20.0
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    TextAlign =2
                    Left =12816
                    Top =1116
                    Width =3228
                    Height =300
                    FontSize =9
                    FontWeight =700
                    Name ="Label62"
                    Caption ="Previous Audit Report Date"
                    GroupTable =2
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    LayoutCachedLeft =12816
                    LayoutCachedTop =1116
                    LayoutCachedWidth =16044
                    LayoutCachedHeight =1416
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =5
                    BackTint =20.0
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin ComboBox
                    RowSourceTypeInt =1
                    OldBorderStyle =0
                    TextAlign =2
                    TextFontFamily =34
                    IMESentenceMode =3
                    Left =96
                    Top =1572
                    Width =3180
                    Height =348
                    FontSize =12
                    FontWeight =700
                    TabIndex =6
                    BackColor =62207
                    Name ="Status"
                    ControlSource ="Status"
                    RowSourceType ="Value List"
                    RowSource ="Cancelled;Completed;Scheduled"
                    ColumnWidths ="567"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =96
                    LayoutCachedTop =1572
                    LayoutCachedWidth =3276
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =3336
                    Top =1572
                    Width =2988
                    Height =348
                    Name ="EmptyCell183"
                    GroupTable =2
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3336
                    LayoutCachedTop =1572
                    LayoutCachedWidth =6324
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6324
                    Top =1572
                    Width =3360
                    Height =348
                    Name ="EmptyCell180"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6324
                    LayoutCachedTop =1572
                    LayoutCachedWidth =9684
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    OldBorderStyle =0
                    TextAlign =2
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    Left =9684
                    Top =1572
                    Width =3132
                    Height =348
                    FontSize =9
                    TabIndex =7
                    ForeColor =855309
                    Name ="Previous_Audit_Report_Number"
                    ControlSource ="Previous_Audit_Report_Number"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9684
                    LayoutCachedTop =1572
                    LayoutCachedWidth =12816
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    BackThemeColorIndex =5
                    BackTint =20.0
                    ForeTint =95.0
                    GroupTable =2
                End
                Begin TextBox
                    OldBorderStyle =0
                    TextAlign =2
                    TextFontFamily =34
                    BackStyle =0
                    IMESentenceMode =3
                    Left =12816
                    Top =1572
                    Width =3228
                    Height =348
                    ColumnWidth =1884
                    FontSize =10
                    TabIndex =8
                    ForeColor =855309
                    Name ="Previous_Audit_Report_Date"
                    ControlSource ="Previous_Audit_Report_Date"
                    Format ="Medium Date"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    ShowDatePicker =1

                    LayoutCachedLeft =12816
                    LayoutCachedTop =1572
                    LayoutCachedWidth =16044
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =5
                    BackTint =20.0
                    ForeTint =95.0
                    GroupTable =2
                End
                Begin Label
                    TextAlign =2
                    Left =228
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label209"
                    Caption ="CL-100.01"
                    GroupTable =5
                    LayoutCachedLeft =228
                    LayoutCachedTop =2208
                    LayoutCachedWidth =1200
                    LayoutCachedHeight =2496
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =1260
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label234"
                    Caption ="CL-100.02"
                    GroupTable =5
                    LayoutCachedLeft =1260
                    LayoutCachedTop =2208
                    LayoutCachedWidth =2232
                    LayoutCachedHeight =2496
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =2292
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label240"
                    Caption ="CL-100.03"
                    GroupTable =5
                    LayoutCachedLeft =2292
                    LayoutCachedTop =2208
                    LayoutCachedWidth =3264
                    LayoutCachedHeight =2496
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =3324
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label246"
                    Caption ="CL-100.04"
                    GroupTable =5
                    LayoutCachedLeft =3324
                    LayoutCachedTop =2208
                    LayoutCachedWidth =4296
                    LayoutCachedHeight =2496
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =4356
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label252"
                    Caption ="CL-100.05"
                    GroupTable =5
                    LayoutCachedLeft =4356
                    LayoutCachedTop =2208
                    LayoutCachedWidth =5328
                    LayoutCachedHeight =2496
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =5388
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label254"
                    Caption ="CL-100.06"
                    GroupTable =5
                    LayoutCachedLeft =5388
                    LayoutCachedTop =2208
                    LayoutCachedWidth =6360
                    LayoutCachedHeight =2496
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =6420
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label256"
                    Caption ="CL-100.07"
                    GroupTable =5
                    LayoutCachedLeft =6420
                    LayoutCachedTop =2208
                    LayoutCachedWidth =7392
                    LayoutCachedHeight =2496
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =7452
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label258"
                    Caption ="CL-100.08"
                    GroupTable =5
                    LayoutCachedLeft =7452
                    LayoutCachedTop =2208
                    LayoutCachedWidth =8424
                    LayoutCachedHeight =2496
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =8484
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label276"
                    Caption ="CL-100.09"
                    GroupTable =5
                    LayoutCachedLeft =8484
                    LayoutCachedTop =2208
                    LayoutCachedWidth =9456
                    LayoutCachedHeight =2496
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =9516
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label278"
                    Caption ="CL-100.10"
                    GroupTable =5
                    LayoutCachedLeft =9516
                    LayoutCachedTop =2208
                    LayoutCachedWidth =10488
                    LayoutCachedHeight =2496
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =10548
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label280"
                    Caption ="CL-100.11"
                    GroupTable =5
                    LayoutCachedLeft =10548
                    LayoutCachedTop =2208
                    LayoutCachedWidth =11520
                    LayoutCachedHeight =2496
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =11580
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label282"
                    Caption ="CL-100.12"
                    GroupTable =5
                    LayoutCachedLeft =11580
                    LayoutCachedTop =2208
                    LayoutCachedWidth =12552
                    LayoutCachedHeight =2496
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =12612
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label284"
                    Caption ="CL-100.13"
                    GroupTable =5
                    LayoutCachedLeft =12612
                    LayoutCachedTop =2208
                    LayoutCachedWidth =13584
                    LayoutCachedHeight =2496
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =13644
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label286"
                    Caption ="CL-100.14"
                    GroupTable =5
                    LayoutCachedLeft =13644
                    LayoutCachedTop =2208
                    LayoutCachedWidth =14616
                    LayoutCachedHeight =2496
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =14676
                    Top =2208
                    Width =972
                    Height =288
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label288"
                    Caption ="CL-100.15"
                    GroupTable =5
                    LayoutCachedLeft =14676
                    LayoutCachedTop =2208
                    LayoutCachedWidth =15648
                    LayoutCachedHeight =2496
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin CheckBox
                    Left =228
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =23
                    Name ="Check208"
                    GroupTable =5

                    LayoutCachedLeft =228
                    LayoutCachedTop =2556
                    LayoutCachedWidth =1200
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =1260
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =9
                    Name ="Check233"
                    GroupTable =5

                    LayoutCachedLeft =1260
                    LayoutCachedTop =2556
                    LayoutCachedWidth =2232
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =2292
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =10
                    Name ="Check239"
                    GroupTable =5

                    LayoutCachedLeft =2292
                    LayoutCachedTop =2556
                    LayoutCachedWidth =3264
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =3324
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =11
                    Name ="Check245"
                    GroupTable =5

                    LayoutCachedLeft =3324
                    LayoutCachedTop =2556
                    LayoutCachedWidth =4296
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =4356
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =12
                    Name ="Check251"
                    GroupTable =5

                    LayoutCachedLeft =4356
                    LayoutCachedTop =2556
                    LayoutCachedWidth =5328
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =5388
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =13
                    Name ="Check253"
                    GroupTable =5

                    LayoutCachedLeft =5388
                    LayoutCachedTop =2556
                    LayoutCachedWidth =6360
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =6420
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =14
                    Name ="Check255"
                    GroupTable =5

                    LayoutCachedLeft =6420
                    LayoutCachedTop =2556
                    LayoutCachedWidth =7392
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =7452
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =15
                    Name ="Check257"
                    GroupTable =5

                    LayoutCachedLeft =7452
                    LayoutCachedTop =2556
                    LayoutCachedWidth =8424
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =8484
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =16
                    Name ="Check275"
                    GroupTable =5

                    LayoutCachedLeft =8484
                    LayoutCachedTop =2556
                    LayoutCachedWidth =9456
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =9516
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =17
                    Name ="Check277"
                    GroupTable =5

                    LayoutCachedLeft =9516
                    LayoutCachedTop =2556
                    LayoutCachedWidth =10488
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =10548
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =18
                    Name ="Check279"
                    GroupTable =5

                    LayoutCachedLeft =10548
                    LayoutCachedTop =2556
                    LayoutCachedWidth =11520
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =11580
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =19
                    Name ="Check281"
                    GroupTable =5

                    LayoutCachedLeft =11580
                    LayoutCachedTop =2556
                    LayoutCachedWidth =12552
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =12612
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =20
                    Name ="Check283"
                    GroupTable =5

                    LayoutCachedLeft =12612
                    LayoutCachedTop =2556
                    LayoutCachedWidth =13584
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =13644
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =21
                    Name ="Check285"
                    GroupTable =5

                    LayoutCachedLeft =13644
                    LayoutCachedTop =2556
                    LayoutCachedWidth =14616
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =14676
                    Top =2556
                    Width =972
                    Height =288
                    TabIndex =22
                    Name ="Check287"
                    GroupTable =5

                    LayoutCachedLeft =14676
                    LayoutCachedTop =2556
                    LayoutCachedWidth =15648
                    LayoutCachedHeight =2844
                    RowStart =1
                    RowEnd =1
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =228
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label421"
                    Caption ="CL100.16"
                    GroupTable =5
                    LayoutCachedLeft =228
                    LayoutCachedTop =2904
                    LayoutCachedWidth =1200
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =1260
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label422"
                    Caption ="CL100.17"
                    GroupTable =5
                    LayoutCachedLeft =1260
                    LayoutCachedTop =2904
                    LayoutCachedWidth =2232
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =2292
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label423"
                    Caption ="CL100.18"
                    GroupTable =5
                    LayoutCachedLeft =2292
                    LayoutCachedTop =2904
                    LayoutCachedWidth =3264
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =3324
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label424"
                    Caption ="CL-100.19"
                    GroupTable =5
                    LayoutCachedLeft =3324
                    LayoutCachedTop =2904
                    LayoutCachedWidth =4296
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =4356
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label425"
                    Caption ="CL-100.20"
                    GroupTable =5
                    LayoutCachedLeft =4356
                    LayoutCachedTop =2904
                    LayoutCachedWidth =5328
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =5388
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label426"
                    Caption ="CL-100.21"
                    GroupTable =5
                    LayoutCachedLeft =5388
                    LayoutCachedTop =2904
                    LayoutCachedWidth =6360
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =6420
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label427"
                    Caption ="CL-100.22"
                    GroupTable =5
                    LayoutCachedLeft =6420
                    LayoutCachedTop =2904
                    LayoutCachedWidth =7392
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =7452
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label428"
                    Caption ="CL-100.23"
                    GroupTable =5
                    LayoutCachedLeft =7452
                    LayoutCachedTop =2904
                    LayoutCachedWidth =8424
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =8484
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label429"
                    Caption ="CL-100.24"
                    GroupTable =5
                    LayoutCachedLeft =8484
                    LayoutCachedTop =2904
                    LayoutCachedWidth =9456
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =9516
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label430"
                    Caption ="CL-100.25"
                    GroupTable =5
                    LayoutCachedLeft =9516
                    LayoutCachedTop =2904
                    LayoutCachedWidth =10488
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =10548
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label431"
                    Caption ="CL-100.26"
                    GroupTable =5
                    LayoutCachedLeft =10548
                    LayoutCachedTop =2904
                    LayoutCachedWidth =11520
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =11580
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label432"
                    Caption ="CL-100.27"
                    GroupTable =5
                    LayoutCachedLeft =11580
                    LayoutCachedTop =2904
                    LayoutCachedWidth =12552
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =12612
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label433"
                    Caption ="CL-100.28"
                    GroupTable =5
                    LayoutCachedLeft =12612
                    LayoutCachedTop =2904
                    LayoutCachedWidth =13584
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =13644
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label434"
                    Caption ="CL-100.29"
                    GroupTable =5
                    LayoutCachedLeft =13644
                    LayoutCachedTop =2904
                    LayoutCachedWidth =14616
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin Label
                    TextAlign =2
                    Left =14676
                    Top =2904
                    Width =972
                    Height =240
                    FontSize =9
                    FontWeight =700
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="Label435"
                    Caption ="CL-100.30"
                    GroupTable =5
                    LayoutCachedLeft =14676
                    LayoutCachedTop =2904
                    LayoutCachedWidth =15648
                    LayoutCachedHeight =3144
                    RowStart =2
                    RowEnd =2
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =2
                    BackThemeColorIndex =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =2
                    ForeTint =90.0
                    GridlineThemeColorIndex =1
                    GroupTable =5
                End
                Begin CheckBox
                    Left =228
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =24
                    Name ="Check436"
                    GroupTable =5

                    LayoutCachedLeft =228
                    LayoutCachedTop =3204
                    LayoutCachedWidth =1200
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =1260
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =25
                    Name ="Check437"
                    GroupTable =5

                    LayoutCachedLeft =1260
                    LayoutCachedTop =3204
                    LayoutCachedWidth =2232
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =2292
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =26
                    Name ="Check438"
                    GroupTable =5

                    LayoutCachedLeft =2292
                    LayoutCachedTop =3204
                    LayoutCachedWidth =3264
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =3324
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =27
                    Name ="Check439"
                    GroupTable =5

                    LayoutCachedLeft =3324
                    LayoutCachedTop =3204
                    LayoutCachedWidth =4296
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =4356
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =28
                    Name ="Check440"
                    GroupTable =5

                    LayoutCachedLeft =4356
                    LayoutCachedTop =3204
                    LayoutCachedWidth =5328
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =5388
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =29
                    Name ="Check441"
                    GroupTable =5

                    LayoutCachedLeft =5388
                    LayoutCachedTop =3204
                    LayoutCachedWidth =6360
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =6420
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =30
                    Name ="Check442"
                    GroupTable =5

                    LayoutCachedLeft =6420
                    LayoutCachedTop =3204
                    LayoutCachedWidth =7392
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =7452
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =31
                    Name ="Check443"
                    GroupTable =5

                    LayoutCachedLeft =7452
                    LayoutCachedTop =3204
                    LayoutCachedWidth =8424
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =8484
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =32
                    Name ="Check444"
                    GroupTable =5

                    LayoutCachedLeft =8484
                    LayoutCachedTop =3204
                    LayoutCachedWidth =9456
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =9516
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =33
                    Name ="Check445"
                    GroupTable =5

                    LayoutCachedLeft =9516
                    LayoutCachedTop =3204
                    LayoutCachedWidth =10488
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =10548
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =34
                    Name ="Check446"
                    GroupTable =5

                    LayoutCachedLeft =10548
                    LayoutCachedTop =3204
                    LayoutCachedWidth =11520
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =11580
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =35
                    Name ="Check447"
                    GroupTable =5

                    LayoutCachedLeft =11580
                    LayoutCachedTop =3204
                    LayoutCachedWidth =12552
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =12612
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =36
                    Name ="Check448"
                    GroupTable =5

                    LayoutCachedLeft =12612
                    LayoutCachedTop =3204
                    LayoutCachedWidth =13584
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =13644
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =37
                    Name ="Check449"
                    GroupTable =5

                    LayoutCachedLeft =13644
                    LayoutCachedTop =3204
                    LayoutCachedWidth =14616
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =2
                    GroupTable =5
                End
                Begin CheckBox
                    Left =14676
                    Top =3204
                    Width =972
                    Height =300
                    TabIndex =38
                    Name ="Check450"
                    GroupTable =5

                    LayoutCachedLeft =14676
                    LayoutCachedTop =3204
                    LayoutCachedWidth =15648
                    LayoutCachedHeight =3504
                    RowStart =3
                    RowEnd =3
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =2
                    GroupTable =5
                End
            End
        End
        Begin PageFooter
            Height =623
            Name ="PageFooterSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
